### ISSUE TITLE
Mod Crashes when loading world

### ISSUE THREAD

**Issue by Attemiff** [finallion/VillagersPlus#11]
[crash-2023-08-14_18.10.15-client.txt](https://github.com/finallion/VillagersPlus_-FABRIC-/files/12340449/crash-2023-08-14_18.10.15-client.txt)

Mod currently crashes when loading saved world or recreating world. Here is the crash report and it initially says it's a datapack issue and offers to boot it in "safemode" with the generic datapack and then it crashes anyways. 

I have a heck ton of mods installed so let me know if you need any other information. The world loads and works fine if I remove the mod.

**Comment by finallion** [comment]
Should be fixed in the newest version!

**Comment by ghost** [comment]
Hello there,

Following up on the comment, I just updated to version 2.1 from Modrinth, and the modpack crashes as soon as you get to new world creation, loading, or re-creation.
By forcibly switching back to version 2.0, the problem is fixed.

Here's the crash report : https://mclo.gs/wZxSrRs

**Comment by Attemiff** [comment]
> Should be fixed in the newest version!
[crash-2023-08-15_12.03.43-client.txt](https://github.com/finallion/VillagersPlus-FABRIC/files/12347054/crash-2023-08-15_12.03.43-client.txt)



Still crashes. This is the new crash report, it looks like it might be conflicting with the Amethyst mod maybe? Thanks for checking it out so quickly!

**Comment by Attemiff** [comment]
> Hello there,
> 
> Following up on the comment, I just updated to version 2.1 from Modrinth, and the modpack crashes as soon as you get to new world creation, loading, or re-creation. By forcibly switching back to version 2.0, the problem is fixed.
> 
> Here's the crash report : https://mclo.gs/wZxSrRs

[crash-2023-08-15_12.07.50-client.txt](https://github.com/finallion/VillagersPlus-FABRIC/files/12347071/crash-2023-08-15_12.07.50-client.txt)


I tried that, it still crashes for me for some reason? This is the crash report for that one.

**Comment by Razokyu** [comment]
> 

Did you tried with this one : https://modrinth.com/mod/villagersplus/version/CzCEYB32 ? It's working with this one (I don't get any crash with it)

**Comment by ghost** [comment]
> > Hello there,
> > Following up on the comment, I just updated to version 2.1 from Modrinth, and the modpack crashes as soon as you get to new world creation, loading, or re-creation. By forcibly switching back to version 2.0, the problem is fixed.
> > Here's the crash report : https://mclo.gs/wZxSrRs
> 
> [crash-2023-08-15_12.07.50-client.txt](https://github.com/finallion/VillagersPlus-FABRIC/files/12347071/crash-2023-08-15_12.07.50-client.txt)
> 
> I tried that, it still crashes for me for some reason? This is the crash report for that one.

Did you tried with this one : https://modrinth.com/mod/villagersplus/version/CzCEYB32 ? It's working with this one (I don't get any crash with it)

**Comment by finallion** [comment]
@Attemiff 
The crash with 2.1 is another unrelated crash. The latest crash report you posted is still the one on 2.0. The second you posted is the one on 2.1. 

Working on a fix.

**Comment by finallion** [comment]
@Attemiff @Razokyu 
Thanks for the reporting and posting. That did help a lot!
I reuploaded the version on curse and modrinth. Tested it with both mods mentioned in the crash.
Let me know, if something comes up again and sorry for the trouble!

**Comment by Attemiff** [comment]
> @Attemiff @Razokyu Thanks for the reporting and posting. That did help a lot! I reuploaded the version on curse and modrinth. Tested it with both mods mentioned in the crash. Let me know, if something comes up again and sorry for the trouble!

That worked!

Thank you so much for fixing it, and it's no trouble at all. Thank you for making and maintaining this mod :)
